# conda env update -n OZ --file environment_OZ.yml
name: OZ
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pip
  - sqlalchemy==1.4.46
  - alembic
  - click
  - faker
  - html2text
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_contrib_nbextensions
  - webcolors
  - jsonschema-with-format-nongpl
  - widgetsnbextension
  - markdown2
  - statsmodels
  - scikit-learn
  - scipy
  - pandas
  - numpy
  - fastparquet
  - pyarrow
  - openpyxl
  - xlsxwriter
  - xlwings
  - matplotlib
  - seaborn
  - faker
  - dataframe_image
  - pandas-profiling
  - pandas-datareader
  - beautifulsoup4
  - requests
  - requests_cache
  - scrapy
  - tqdm
  - typeguard
  - typer
  - typing
  - python-dotenv
  - dynaconf
  - lxml
  - black
  - isort
  - tox
  - pytest-httpserver
  - pytest-cov
  - pytest-remotedata
  - pytest
  - dunamai
  - sphinx
  - sphinx-autobuild
  - sphinx-rtd-theme
  - myst-parser
  - recommonmark

  - pip:
      - ipyaggrid
      - playwright
