# conda env update -n OZ --file environment_OZ.yml
name: OZ
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pip>=23.0
  - sqlalchemy==1.4.46
  - alembic>=1.9.0
  - click>=8.1.3
  - faker>=16.6.1
  - html2text>=2020.1.16
  - ipykernel>=6.21.1
  - ipython>=8.9.0
  - ipywidgets>=8.0.4
  - jupyter>=1.0.0
  - widgetsnbextension>=3.5.2 
  - markdown2>=2.4.7
  - scipy>=1.9.3 
  - pandas>=1.5.3
  - numpy>=1.24.2
  - openpyxl>=3.1.0
  - xlsxwriter>3.0.0
  - xlwings>=0.29.0
  - matplotlib>=3.6.3 
  - seaborn>=0.12.2
  - faker>=16.6.1 
  - dataframe_image>=0.1.1
  - pandas-profiling>=3.6.3
  - beautifulsoup4>=4.11.2
  - requests>=2.28.2
  - scrapy>=2.8.0
  - tqdm>=4.64.1
  - typeguard>=2.13.3
  - typer>=0.7.0
  - typing>=3.10.0.0
  - lxml>=4.9.2
  - black>=20.8b1 
  - isort>=5.12.0
  - tox>=4.3.0 
  - pytest-httpserver>=1.0.4 
  - pytest-cov>=2.12.1 
  - pytest-remotedata>=0.3.3 
  - pytest>=7.2.1 
  - dunamai>=1.15.0 
  - sphinx>=5.3.0
  - sphinx-autobuild>=2021.3.14 
  - sphinx-rtd-theme>=1.1.1 
  - myst-parser>=0.18.1 
  - recommonmark>=0.7.1 

  - pip:
      - ipyaggrid>=0.3.1